import arcpy
import requests
import zipfile
import io

#set working environment
proj_dir = r'C:\Users\MrJDF\Desktop\Arc1_lab02_v02'
arcpy.env.workspace = proj_dir
arcpy.env.workspace

prism_url = r'https://www.prism.oregonstate.edu/fetchData.php'
prism_parameters = r'type=all_bil&kind=normals&spatial=4km&elem=ppt&temporal=annual'
full_prism_path = prism_url + '?' + prism_parameters
print(full_prism_path)

#get it with requests

req_prism = requests.post(full_prism_path)
req_prism #sucess will give response 200

#Extract the zipped file retrieved
zipped_response = zipfile.ZipFile(
    io.BytesIO(req_prism.content
    )).extractall(proj_dir)

# block of code from model builder following the space time tutorial
# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-11-01 18:26:16
"""
# import arcpy #already done

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\MrJDF\Desktop\Arc1_lab02_v02\Arc1_lab02_v02.gdb", workspace=r"C:\Users\MrJDF\Desktop\Arc1_lab02_v02\Arc1_lab02_v02.gdb"):
        Arc1_lab02_v02_gdb = "C:\\Users\\MrJDF\\Desktop\\Arc1_lab02_v02\\Arc1_lab02_v02.gdb"
        PRISM_data = "C:\\Users\\MrJDF\\Desktop\\Arc1_lab02_v02\\PRISM-data"
        Arc1_lab02_v02 = "."
        Footprint = "Annual30yrNormals\\Footprint"

        # Process: Create Mosaic Dataset (Create Mosaic Dataset) (management)
        Annual30yrNormals = arcpy.management.CreateMosaicDataset(in_workspace=Arc1_lab02_v02_gdb, in_mosaicdataset_name="Annual30yrNormals", coordinate_system="GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", num_bands=None, pixel_type="", product_definition="NONE", product_band_definitions=[])[0]

        # Process: Add Rasters To Mosaic Dataset (Add Rasters To Mosaic Dataset) (management)
        Annual30yrNormals_3_ = arcpy.management.AddRastersToMosaicDataset(in_mosaic_dataset=Annual30yrNormals, raster_type="Raster Dataset", input_path=[PRISM_data], update_cellsize_ranges="UPDATE_CELL_SIZES", update_boundary="UPDATE_BOUNDARY", update_overviews="NO_OVERVIEWS", maximum_pyramid_levels=None, maximum_cell_size=0, minimum_dimension=1500, spatial_reference="", filter="", sub_folder="SUBFOLDERS", duplicate_items_action="ALLOW_DUPLICATES", build_pyramids="NO_PYRAMIDS", calculate_statistics="NO_STATISTICS", build_thumbnails="NO_THUMBNAILS", operation_description="", force_spatial_reference="NO_FORCE_SPATIAL_REFERENCE", estimate_statistics="NO_STATISTICS", aux_inputs=[], enable_pixel_cache="NO_PIXEL_CACHE", cache_location="")[0]
        
        # Process: Calculate Field (3) (Calculate Field) (management)
        Footprint_2_ = arcpy.management.CalculateField(in_table=Footprint, field="Variable", expression="\"Annual30yrNormals\"", expression_type="PYTHON3", code_block="", field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

        # Process: Calculate Field (4) (Calculate Field) (management)
        Footprint_4_ = arcpy.management.CalculateField(in_table=Footprint, field="Timestamp", expression="DateAdd(Date(1991,0,1), $feature.OBJECTID-1, 'year')", expression_type="ARCADE", code_block="", field_type="DATE", enforce_domains="NO_ENFORCE_DOMAINS")[0]

        # Process: Build Multidimensional Info (Build Multidimensional Info) (md)
        Annual30yrNormals_6_ = arcpy.md.BuildMultidimensionalInfo(in_mosaic_dataset=Annual30yrNormals_3_, variable_field="Variable", dimension_fields=[["Timestamp", "", ""]], variable_desc_units=[], delete_multidimensional_info="NO_DELETE_MULTIDIMENSIONAL_INFO")[0]

        # Process: Make Multidimensional Raster Layer (Make Multidimensional Raster Layer) (md)
        Annual30yrNormals_MultidimLayer = "Annual30yrNormals_MultidimLayer"
        arcpy.md.MakeMultidimensionalRasterLayer(in_multidimensional_raster=Annual30yrNormals_6_, out_multidimensional_raster_layer=Annual30yrNormals_MultidimLayer, variables=["Annual30yrNormals"], dimension_def="ALL", dimension_ranges=[], dimension_values=[], dimension="", start_of_first_iteration="", end_of_first_iteration="", iteration_step=None, iteration_unit="", template="-125.020833333333 24.0624999997935 -66.4791666661985 49.9375000000005 GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", dimensionless="DIMENSIONS", spatial_reference="")

        # Process: Create Space Time Cube From Multidimensional Raster Layer (Create Space Time Cube From Multidimensional Raster Layer) (stpm)
        PRISM_30yrAnn_spacetimecube_nc = "C:\\Users\\MrJDF\\Desktop\\Arc1_lab02_v02\\PRISM-30yrAnn_spacetimecube.nc"
        arcpy.stpm.CreateSpaceTimeCubeMDRasterLayer(in_md_raster=Annual30yrNormals_MultidimLayer, output_cube=PRISM_30yrAnn_spacetimecube_nc, fill_empty_bins="ZEROS")

       
if __name__ == '__main__':
    Model()





# visualize spacetime cube in 3D
arcpy.stpm.VisualizeSpaceTimeCube3D(r"C:\Users\MrJDF\Desktop\Arc1_lab02_v02\PRISM-30yrAnn_spacetimecube.nc", "ANNUAL30YRNORMALS_NONE_ZEROS", "VALUE", r"C:\Users\MrJDF\Desktop\Arc1_lab02_v02\Arc1_lab02_v02.gdb\PRISM30yrAnn_spacetimecube_VisualizeSpaceTimeCube3D")
